server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    data-username: root
    data-password: root
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka
# 启动feign的熔断器功能
feign:
  hystrix:
    enabled: true
  client:
    config:
      # 对应的微服务
      drug:
        logger-level: FULL
        # 连接超时时间，默认2s
        connect-timeout:  5000
        # 请求处理超时时间，默认5s
        read-timeout: 10000
  # 默认使用JDK原生的 URLConnection
  httpclient:
    # 导入依赖，开启开关
    enabled: true

# 在yml配置文件中执行 Client 的日志级别才能正常输出日志，格式是"logging.level.feign接口包路径=debug"
logging:
  level:
    com.neuedu.his.drug.client: debug

